language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - "RAILS_VERSION=3.2.13"
  - "RAILS_VERSION=4.0.0"
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake app:db:test:prepare
  - bundle exec rspec spec/