language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - "RAILS_VERSION=3.2.13"
  - "RAILS_VERSION=4.0.0"
before_script: 
  - psql -c 'create database tempora_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake app:db:test:prepare
  - bundle exec rspec spec/
gemfile:
#  - Gemfile
  - Gemfile.ruby1.9
  - Gemfile.ruby2.0
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: Gemfile.ruby2.0
      env: "RAILS_VERSION=3.2.13"
    - rvm: 1.9.3
      gemfile: Gemfile.ruby2.0
      env: "RAILS_VERSION=4.0.0"
