defaults: &defaults
  adapter: postgresql
  pool: 5010
  min_messages: warning

development:
  database: tempora_development
  host: localhost
  <<: *defaults

test:
  database: tempora_test
  host: localhost
  <<: *defaults
